### ISSUE TITLE
Creating the initial tables

### ISSUE THREAD

**Issue by Forethinker** [eventray/horus#48]
I see that horus is being used by hypothesis to do the authentication, it inherits the model straight up. But I do not see anywhere where horus utilize sqlalchemy to initialize the table in the database. Is this step supposed to be manual?

**Comment by tilgovi** [comment]
I think horus does not do this automatically in any way. The models are implemented as mixins that are meant to be inherited. A typical usage is to inherit both the mixin and the SQLAlchemy declarative base model. For example, see https://github.com/eventray/horus/blob/master/horus/tests/models.py

In hypothesis/h we do this by using the `pyramid_basemodel` package. In that case, `pyramid_basemodel` automatically creates the models when it's included if the `basemodel.should_create_all` setting is `True`.

**Comment by uranther** [comment]
@Forethinker The way I did this was to use the `initialize_yourproject_db` script which comes with the Pyramid project scaffold. You may need to modify `initializedb` under `scripts/` to explicitly tell it to add the horus models under `with transaction.manager:`, also making sure that Base.metadata is the one which is inherited from horus `BaseModel`.
